# Generated by Django 3.2.4 on 2021-06-23 11:31

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210623_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to=books.models.cover_path),
        ),
    ]
